name: scroll_wheel_date_picker_example
description: "Example app for scroll_wheel_date_picker"

publish_to: "none"

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  scroll_wheel_date_picker:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
