name: wheel_date_picker
description: "A Flutter package for a scrollable wheel-type date picker like in TikTok."
version: 0.0.1

homepage: https://github.com/Fingertips18/wheel-date-picker
repository: https://github.com/Fingertips18/wheel-date-picker

environment:
  sdk: ">=3.2.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
